// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/api/pb/gateway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message is one chat message.
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_api_pb_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ChatRequest is a gRPC chat completion request.
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_internal_api_pb_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// ChatResponse is the gateway reply with routing metadata.
type ChatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Intent           string                 `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"`
	Layer            int32                  `protobuf:"varint,3,opt,name=layer,proto3" json:"layer,omitempty"`
	Content          string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,5,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,6,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_internal_api_pb_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_pb_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_pb_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatResponse) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *ChatResponse) GetLayer() int32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *ChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatResponse) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *ChatResponse) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

var File_internal_api_pb_gateway_proto protoreflect.FileDescriptor

const file_internal_api_pb_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/api/pb/gateway.proto\x12\agateway\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"Q\n" +
	"\vChatRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12,\n" +
	"\bmessages\x18\x02 \x03(\v2\x10.gateway.MessageR\bmessages\"\xb8\x01\n" +
	"\fChatResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06intent\x18\x02 \x01(\tR\x06intent\x12\x14\n" +
	"\x05layer\x18\x03 \x01(\x05R\x05layer\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12#\n" +
	"\rprompt_tokens\x18\x05 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x06 \x01(\x03R\x10completionTokens2>\n" +
	"\aGateway\x123\n" +
	"\x04Chat\x12\x14.gateway.ChatRequest\x1a\x15.gateway.ChatResponseB\"Z agent-gateway/internal/api/pb;pbb\x06proto3"

var (
	file_internal_api_pb_gateway_proto_rawDescOnce sync.Once
	file_internal_api_pb_gateway_proto_rawDescData []byte
)

func file_internal_api_pb_gateway_proto_rawDescGZIP() []byte {
	file_internal_api_pb_gateway_proto_rawDescOnce.Do(func() {
		file_internal_api_pb_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_pb_gateway_proto_rawDesc), len(file_internal_api_pb_gateway_proto_rawDesc)))
	})
	return file_internal_api_pb_gateway_proto_rawDescData
}

var file_internal_api_pb_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_api_pb_gateway_proto_goTypes = []any{
	(*Message)(nil),      // 0: gateway.Message
	(*ChatRequest)(nil),  // 1: gateway.ChatRequest
	(*ChatResponse)(nil), // 2: gateway.ChatResponse
}
var file_internal_api_pb_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.ChatRequest.messages:type_name -> gateway.Message
	1, // 1: gateway.Gateway.Chat:input_type -> gateway.ChatRequest
	2, // 2: gateway.Gateway.Chat:output_type -> gateway.ChatResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_api_pb_gateway_proto_init() }
func file_internal_api_pb_gateway_proto_init() {
	if File_internal_api_pb_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_pb_gateway_proto_rawDesc), len(file_internal_api_pb_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_pb_gateway_proto_goTypes,
		DependencyIndexes: file_internal_api_pb_gateway_proto_depIdxs,
		MessageInfos:      file_internal_api_pb_gateway_proto_msgTypes,
	}.Build()
	File_internal_api_pb_gateway_proto = out.File
	file_internal_api_pb_gateway_proto_goTypes = nil
	file_internal_api_pb_gateway_proto_depIdxs = nil
}
